FROM ubuntu

RUN dd if=/dev/urandom of=random_data1.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data2.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data3.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data4.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data5.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data6.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data7.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data8.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data9.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data10.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data11.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data12.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data13.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data14.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data15.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data16.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data17.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data18.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data19.bin bs=1M count=95
RUN dd if=/dev/urandom of=random_data20.bin bs=1M count=95